services:
  localstack:
    image: localstack/localstack:3.1.0
    volumes:
      - ./localstack.sh:/etc/localstack/init/ready.d/localstack.sh
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,sns
      - DEBUG=1s
      - AWS_ACCESS_KEY_ID=localstack
      - AWS_SECRET_ACCESS_KEY=localstack
      - AWS_DEFAULT_REGION=sa-east-1